"""
System-wide constants.
"""
from __future__ import annotations

# Pagination Defaults
DEFAULT_PAGE = 1
DEFAULT_PER_PAGE = 20
MAX_PER_PAGE = 100

# Datetime formats
ISO_DATETIME_FORMAT = "%Y-%m-%dT%H:%M:%S%z"

# Message direction
MESSAGE_DIRECTION_INBOUND = "inbound"
MESSAGE_DIRECTION_OUTBOUND = "outbound"

# Ticket priority
TICKET_PRIORITY_LOW = "LOW"
TICKET_PRIORITY_MEDIUM = "MEDIUM"
TICKET_PRIORITY_HIGH = "HIGH"
TICKET_PRIORITY_URGENT = "URGENT"

# Ticket status
TICKET_STATUS_OPEN = "OPEN"
TICKET_STATUS_IN_PROGRESS = "IN_PROGRESS"
TICKET_STATUS_WAITING = "WAITING_ON_CUSTOMER"
TICKET_STATUS_RESOLVED = "RESOLVED"
TICKET_STATUS_CLOSED = "CLOSED"
