"""add_client_and_employee

Revision ID: 597e2cc997f8
Revises: 0003_add_tickets_endpoints
Create Date: 2026-06-12 08:21:35.385946

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '597e2cc997f8'
down_revision = '0003_add_tickets_endpoints'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encryption_metadata',
    sa.Column('key_id', sa.String(length=255), nullable=False),
    sa.Column('algorithm', sa.String(length=50), nullable=False),
    sa.Column('rotation_count', sa.Integer(), nullable=False),
    sa.Column('last_rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('api_keys',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index('ix_api_keys_org_active', 'api_keys', ['organization_id', 'is_active'], unique=False)
    op.create_table('audit_logs',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_org_action', 'audit_logs', ['organization_id', 'action'], unique=False)
    op.create_index('ix_audit_logs_org_created', 'audit_logs', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_audit_logs_user', 'audit_logs', ['user_id'], unique=False)
    op.create_table('clients',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clients_org_name', 'clients', ['organization_id', 'name'], unique=False)
    op.create_index('ix_clients_org_phone', 'clients', ['organization_id', 'phone'], unique=False)
    op.create_table('employees',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_employees_org_department', 'employees', ['organization_id', 'department'], unique=False)
    op.create_index('ix_employees_org_email', 'employees', ['organization_id', 'email'], unique=True)
    op.create_table('notifications',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_created', 'notifications', ['created_at'], unique=False)
    op.create_index('ix_notifications_org_user', 'notifications', ['organization_id', 'user_id'], unique=False)
    op.create_index('ix_notifications_unread', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('prompt_templates',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('user_prompt', sa.Text(), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prompt_templates_org_category', 'prompt_templates', ['organization_id', 'category'], unique=False)
    op.create_index('ix_prompt_templates_org_name', 'prompt_templates', ['organization_id', 'name'], unique=True)
    op.create_table('roles_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('workflows',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trigger', sa.String(length=100), nullable=False),
    sa.Column('trigger_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.String(length=50), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workflows_org_active', 'workflows', ['organization_id', 'is_active'], unique=False)
    op.create_index('ix_workflows_org_trigger', 'workflows', ['organization_id', 'trigger'], unique=False)
    op.create_table('activity_logs',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('activity_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activity_logs_org_type', 'activity_logs', ['organization_id', 'activity_type'], unique=False)
    op.create_index('ix_activity_logs_user', 'activity_logs', ['user_id'], unique=False)
    op.create_table('agent_configs',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('config_key', sa.String(length=255), nullable=False),
    sa.Column('config_value', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['ai_agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_configs_agent_key', 'agent_configs', ['agent_id', 'config_key'], unique=True)
    op.create_table('webhook_logs',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('endpoint_config_id', sa.UUID(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_config_id'], ['endpoint_configs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhook_logs_endpoint', 'webhook_logs', ['endpoint_config_id'], unique=False)
    op.create_index('ix_webhook_logs_org_event', 'webhook_logs', ['organization_id', 'event_type'], unique=False)
    op.create_table('workflow_executions',
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workflow_execs_conv', 'workflow_executions', ['conversation_id'], unique=False)
    op.create_index('ix_workflow_execs_workflow', 'workflow_executions', ['workflow_id'], unique=False)
    
    # Create PostgreSQL Enum Types
    postgresql.ENUM('ACTIVE', 'WAITING', 'BOT_HANDLING', 'HUMAN_HANDLING', 'ESCALATED', 'RESOLVED', 'CLOSED', name='conversationstatus').create(op.get_bind(), checkfirst=True)
    postgresql.ENUM('WHATSAPP', 'WHATSAPP_BUSINESS', name='conversationchannel').create(op.get_bind(), checkfirst=True)
    postgresql.ENUM('INBOUND', 'OUTBOUND', name='messagedirection').create(op.get_bind(), checkfirst=True)
    postgresql.ENUM('TEXT', 'IMAGE', 'AUDIO', 'VIDEO', 'DOCUMENT', 'LOCATION', 'CONTACTS', 'INTERACTIVE', 'TEMPLATE', 'REACTION', 'STICKER', 'SYSTEM', name='messagetype').create(op.get_bind(), checkfirst=True)
    postgresql.ENUM('PENDING', 'SENT', 'DELIVERED', 'READ', 'FAILED', name='messagestatus').create(op.get_bind(), checkfirst=True)
    
    # Update existing column data to uppercase to match Postgres Enum values
    op.execute("UPDATE conversations SET status = UPPER(status)")
    op.execute("UPDATE conversations SET channel = UPPER(channel)")
    op.execute("UPDATE messages SET direction = UPPER(direction)")
    op.execute("UPDATE messages SET message_type = UPPER(message_type)")
    op.execute("UPDATE messages SET status = UPPER(status)")

    # 1. conversations.status
    op.alter_column('conversations', 'status', server_default=None)
    op.alter_column('conversations', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('ACTIVE', 'WAITING', 'BOT_HANDLING', 'HUMAN_HANDLING', 'ESCALATED', 'RESOLVED', 'CLOSED', name='conversationstatus'),
               existing_nullable=False,
               postgresql_using="status::conversationstatus")
    op.alter_column('conversations', 'status', server_default='ACTIVE')

    # 2. conversations.channel
    op.alter_column('conversations', 'channel', server_default=None)
    op.alter_column('conversations', 'channel',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('WHATSAPP', 'WHATSAPP_BUSINESS', name='conversationchannel'),
               existing_nullable=False,
               postgresql_using="channel::conversationchannel")
    op.alter_column('conversations', 'channel', server_default='WHATSAPP')

    op.create_index('ix_conversations_last_msg', 'conversations', ['last_message_at'], unique=False)
    op.drop_index(op.f('ix_chunk_emb_ivfflat'), table_name='document_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    
    # 3. messages.direction
    op.alter_column('messages', 'direction',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('INBOUND', 'OUTBOUND', name='messagedirection'),
               existing_nullable=False,
               postgresql_using="direction::messagedirection")

    # 4. messages.message_type
    op.alter_column('messages', 'message_type', server_default=None)
    op.alter_column('messages', 'message_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('TEXT', 'IMAGE', 'AUDIO', 'VIDEO', 'DOCUMENT', 'LOCATION', 'CONTACTS', 'INTERACTIVE', 'TEMPLATE', 'REACTION', 'STICKER', 'SYSTEM', name='messagetype'),
               existing_nullable=False,
               postgresql_using="message_type::messagetype")
    op.alter_column('messages', 'message_type', server_default='TEXT')

    # 5. messages.status
    op.alter_column('messages', 'status', server_default=None)
    op.alter_column('messages', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'SENT', 'DELIVERED', 'READ', 'FAILED', name='messagestatus'),
               existing_nullable=False,
               postgresql_using="status::messagestatus")
    op.alter_column('messages', 'status', server_default='PENDING')
    op.create_index('ix_messages_ai_generated', 'messages', ['ai_generated'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_ai_generated', table_name='messages')
    op.alter_column('messages', 'status',
               existing_type=sa.Enum('PENDING', 'SENT', 'DELIVERED', 'READ', 'FAILED', name='messagestatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('messages', 'message_type',
               existing_type=sa.Enum('TEXT', 'IMAGE', 'AUDIO', 'VIDEO', 'DOCUMENT', 'LOCATION', 'CONTACTS', 'INTERACTIVE', 'TEMPLATE', 'REACTION', 'STICKER', 'SYSTEM', name='messagetype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'text'::character varying"))
    op.alter_column('messages', 'direction',
               existing_type=sa.Enum('INBOUND', 'OUTBOUND', name='messagedirection'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.create_index(op.f('ix_chunk_emb_ivfflat'), 'document_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index('ix_conversations_last_msg', table_name='conversations')
    op.alter_column('conversations', 'channel',
               existing_type=sa.Enum('WHATSAPP', 'WHATSAPP_BUSINESS', name='conversationchannel'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'whatsapp'::character varying"))
    op.alter_column('conversations', 'status',
               existing_type=sa.Enum('ACTIVE', 'WAITING', 'BOT_HANDLING', 'HUMAN_HANDLING', 'ESCALATED', 'RESOLVED', 'CLOSED', name='conversationstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_index('ix_workflow_execs_workflow', table_name='workflow_executions')
    op.drop_index('ix_workflow_execs_conv', table_name='workflow_executions')
    op.drop_table('workflow_executions')
    op.drop_index('ix_webhook_logs_org_event', table_name='webhook_logs')
    op.drop_index('ix_webhook_logs_endpoint', table_name='webhook_logs')
    op.drop_table('webhook_logs')
    op.drop_index('ix_agent_configs_agent_key', table_name='agent_configs')
    op.drop_table('agent_configs')
    op.drop_index('ix_activity_logs_user', table_name='activity_logs')
    op.drop_index('ix_activity_logs_org_type', table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index('ix_workflows_org_trigger', table_name='workflows')
    op.drop_index('ix_workflows_org_active', table_name='workflows')
    op.drop_table('workflows')
    op.drop_table('roles_permissions')
    op.drop_index('ix_prompt_templates_org_name', table_name='prompt_templates')
    op.drop_index('ix_prompt_templates_org_category', table_name='prompt_templates')
    op.drop_table('prompt_templates')
    op.drop_index('ix_notifications_unread', table_name='notifications')
    op.drop_index('ix_notifications_org_user', table_name='notifications')
    op.drop_index('ix_notifications_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_employees_org_email', table_name='employees')
    op.drop_index('ix_employees_org_department', table_name='employees')
    op.drop_table('employees')
    op.drop_index('ix_clients_org_phone', table_name='clients')
    op.drop_index('ix_clients_org_name', table_name='clients')
    op.drop_table('clients')
    op.drop_index('ix_audit_logs_user', table_name='audit_logs')
    op.drop_index('ix_audit_logs_resource', table_name='audit_logs')
    op.drop_index('ix_audit_logs_org_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_org_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_api_keys_org_active', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('system_settings')
    op.drop_table('permissions')
    op.drop_table('encryption_metadata')
    
    # Drop PostgreSQL Enum Types
    postgresql.ENUM('conversationstatus').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM('conversationchannel').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM('messagedirection').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM('messagetype').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM('messagestatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
